version: 0.2

phases:
  install:
    commands:
      - sudo apt-get -y install npm
  pre_build:
    commands:
      - rm -rf .git README.md
  build:
    commands:
      - npm install
artifacts:
  files:
    - '**/*'
  discard-paths: no
