version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y nodejs
      - sudo apt-get install -y npm
  pre_build:
    commands:
      - node -v && npm -v
      - rm -rf .git README.md
  build:
    commands:
      - npm install
artifacts:
  files:
    - '**/*'
  discard-paths: no
