version: 0.2

phases:
  update_system:
    commands:
      - sudo apt-get update
  install_nodejs:
    commands:
      - sudo apt-get install -y nodejs
  install_npm:
    commands:
      - sudo apt-get install -y npm
  check_versions:
    commands:
      - node -v && npm -v
  remove_surplus_files:
    commands:
      - rm -rf .git README.md
  build:
    commands:
      - npm install
artifacts:
  files:
    - '**/*'
  discard-paths: no
