version: 0.2

phases:
  install:
    commands:
      - echo 'this is installation steps'
  pre_build:
    commands:
      - rm -rf .git README.md
  build:
    commands:
      - npm install
artifacts:
  files:
    - '**/*'
  discard-paths: no
